### ISSUE TITLE
How to use optical flow data ?

### ISSUE THREAD

**Issue by yellowYuga** [ydrive/EasySynth#27]
I use this code to covert optical flow data.But it doesn't look right.
Here is  my python code:
```
import cv2
import torch
import torch.nn as nn
import numpy as np
def img2flow(img,scale):
    '''
    :param img: cv img bgr
    :param scale: optical scale
    :return: dx dy tensor
    '''
    h = img.shape[0]
    w = img.shape[1]
    img = cv2.cvtColor(img,cv2.COLOR_BGR2HSV) #h is angle ,s is intensity
    ang = img[:,:,0] #* 2 *np.pi / 180
    mag = img[:,:,1]  / scale
    dx ,dy = cv2.polarToCart(mag,ang,angleInDegrees=True)
    dx = w * dx
    dy = h *dy
    dx = torch.Tensor(dx).unsqueeze(0).unsqueeze(0)
    dy = torch.Tensor(dy).unsqueeze(0).unsqueeze(0)
    #print(dx.shape)
    print(dx)
    print(dx.max())




    return dx ,dy
def read_img2tensor(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    img = img.transpose(2, 0, 1)
    tensor = torch.Tensor(img).float().unsqueeze(0)

    #1*3*h*w

    return tensor
def vis_tensor(winname,tensor):
    #tensor 1 3 h w
    mat = tensor.squeeze().detach().numpy()
    mat = np.uint8(mat)  # float32-->uint8
    mat = mat.transpose(1, 2, 0)  # mat_shape: (982, 814，3)
    mat = cv2.cvtColor(mat,cv2.COLOR_BGR2RGB)
    #cv2.imshow(winname,mat)
    cv2.imwrite(r'E:\data\EasySynth_test2/'+winname+'.jpg',mat)
    return 0

def warp(x, flo):
    """
    warp an image/tensor (im2) back to im1, according to the optical flow
    x: [B, C, H, W] (im2)
    flo: [B, 2, H, W] flow
    """
    B, C, H, W = x.size()
    # mesh grid
    xx = torch.arange(0, W).view(1, -1).repeat(H, 1)
    yy = torch.arange(0, H).view(-1, 1).repeat(1, W)
    xx = xx.view(1, 1, H, W).repeat(B, 1, 1, 1)
    yy = yy.view(1, 1, H, W).repeat(B, 1, 1, 1)
    grid = torch.cat((xx, yy), 1).float()

    # if x.is_cuda:
    #     grid = grid.cuda()
    vgrid = grid + flo

    # scale grid to [-1,1]
    vgrid[:, 0, :, :] = 2.0 * vgrid[:, 0, :, :].clone() / max(W - 1, 1) - 1.0
    vgrid[:, 1, :, :] = 2.0 * vgrid[:, 1, :, :].clone() / max(H - 1, 1) - 1.0

    vgrid = vgrid.permute(0, 2, 3, 1)
    output = nn.functional.grid_sample(x, vgrid,mode="bilinear",align_corners=False)
    mask = torch.autograd.Variable(torch.ones(x.size()))
    mask = nn.functional.grid_sample(mask, vgrid)

    # if W==128:
    # np.save('mask.npy', mask.cpu().data.numpy())
    # np.save('warp.npy', output.cpu().data.numpy())

    mask[mask < 0.9999] = 0
    mask[mask > 0] = 1

    return output * mask


if __name__ == '__main__':
    #'exr'
    path0 = r'E:\data\EasySynth_test\ColorImage/'+'testSeq.0008.jpeg'
    path1 = r'E:\data\EasySynth_test\ColorImage/' + 'testSeq.0007.jpeg'
    #flow_path = r'E:\data\EasySynth_test\OpticalFlowImage_scale2/' + 'testSeq.0008.exr'
    flow_path = r'E:\data\EasySynth_test\OpticalFlowImage_scale1/' + 'testSeq.0008.exr'
    flow_img = cv2.imread(flow_path, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
    #flow_img = cv2.imread(flow_path)
    print(flow_img.max())
    dx , dy = img2flow(flow_img,scale=1)
    flow = torch.cat((dx,dy),dim=1)

    #test
    #read img0 and img1
    img0 = read_img2tensor(path0)
    img1 = read_img2tensor(path1)
    img1_0 =warp(img1,flow)

    vis_tensor('0',img0)
    vis_tensor('0warp',img1_0)
```
testSeq.0007.jpeg:

![testSeq 0007](https://user-images.githubusercontent.com/32639257/161232503-81636fe4-ba4f-425a-8b4d-b1e907501ac4.jpeg)
testSeq.0008.jpeg:
![testSeq 0008](https://user-images.githubusercontent.com/32639257/161232566-5a2e7798-a7be-4f19-9f9e-6537fb81e8dc.jpeg)
And after warp 7 to 8 with testSeq.0008.exr looks like this:
![0warp](https://user-images.githubusercontent.com/32639257/161232908-3560d454-75b2-4f31-88a4-5968f373dc0b.jpg)
I also tried other ways of warp. such from 0008.jpeg warp to 0007.jpeg. 
Is there something wrong?

Besides ,when I use .jpeg format to get optical flow data with replace code cv2.imread,the value will be far out of range.And in this case scale doesn't seem to be used correctly in my code.

**Comment by yellowYuga** [comment]
Besides,when I set output img width and height to other such as 1024 * 768，optical flow data will be wrong.

**Comment by NikolaJov96** [comment]
Hi @yellowYuga, thanks for reaching out.
I noted the output image size bug, hope using the default image size, for now, is not a big issue for you.
As for the optical flow conversion, I will have to give it a try and get back to you in a few days.

**Comment by NikolaJov96** [comment]
Hey @yellowYuga, tried your code on my example and got it to work correctly with one small change.
In order to get the correct flow that maps **image0** to **image1**, change the return from the `img2flow` function from `return dx, dy` to `return -dx, -dy` (also change `warp(img1,flow)` to `warp(img0,flow)`).

This is due to EasySynth exporting "inverted" optical flow, we will fix this in the next update.

Here are my outputs:

Image Seq.0013.jpeg:
![Seq 0013](https://user-images.githubusercontent.com/8226562/161519112-b374c16d-d203-48c2-9f4d-cf373f47ba3b.jpeg)

Image Seq.0014.jpeg:
![Seq 0014](https://user-images.githubusercontent.com/8226562/161519143-73d2cc02-cfee-4c04-a249-023b013a1fc3.jpeg)

Image Seq.0013.jpeg with applied optical flow:
![0warp](https://user-images.githubusercontent.com/8226562/161519298-d66d0c82-676e-4686-95ca-84a9aecfde67.jpg)

Note that artifacts, like double poles, appear only in places that are not visible on the base image, so there is no information on what should be displayed on those pixels.

Thanks for the great example code, I'll incorporate it into the readme!
