### ISSUE TITLE
Creating a stereo camera ground truth rig is difficult with camera's within blueprints or attached to other actors

### ISSUE THREAD

**Issue by David-Herman** [ydrive/EasySynth#33]
Creating a stereo camera ground truth rig is difficult with cameras within blueprints or cine camera actors attached to other actors (see image below). In my workflow, I have attempted to use take recorder to record a vehicle blueprint with attached camera component and as well as using a level sequence and attaching a camera to a primary camera actor which I navigate in the level sequence. For the attached camera or camera within the blueprint, the camera poses can not be exported (EasySynt. The primary camera's camera pose in the example below can be exported.

![image](https://user-images.githubusercontent.com/22305345/175104419-4fa46b14-653a-4c75-a060-00c7a9214277.png)

![image](https://user-images.githubusercontent.com/22305345/175105588-cdfe6139-1774-4029-8a22-f11bd807c2e3.png)

**Comment by NikolaJov96** [comment]
Hi @David-Herman, sorry for the late reply. I am aware of the issue and will be working on this and other improvements in the coming weeks. Unfortunately, I can't help you at this moment.
