### ISSUE TITLE
Version for Unreal 5.3

### ISSUE THREAD

**Issue by chisio23** [ydrive/EasySynth#67]
Hi! The Plugin will be updated to UE 5.3?? Thanks!

**Comment by NikolaJov96** [comment]
Hi @chisio23,

It is on the roadmap, but I cannot give you an estimate of when will it happen.

**Comment by thomasctobin** [comment]
Would also like it for 5.2.1!

**Comment by ERGOWHO** [comment]
> Hi @chisio23,
> 
> It is on the roadmap, but I cannot give you an estimate of when will it happen.

Hi Is the current version works with 5.0? I added it as plugin and it does not show any icon on my window like the demo video does. So I do not know how to open the easysynth window.

**Comment by NikolaJov96** [comment]
I hope we will be able to make new releases for UE 5.2 and 5.3 at some point, but there is still no expected date.
The most recent version is compatible with 5.1, while the previous release is compatible with 5.0 (https://github.com/ydrive/EasySynth/releases/tag/v2.0.0).

Nothing comes to my mind as to why the icon would not appear.

**Comment by NikolaJov96** [comment]
Hi, releases for all major 5.x UE versions are now available on the UE marketplace and in the dedicated Github releases.
