### ISSUE TITLE
UE5.1  incorrect estimation optical flow in dy direction

### ISSUE THREAD

**Issue by zhangjialu11** [ydrive/EasySynth#68]
hi,  I find the optical flow is incorrect when camera move in dy without dx. 
in this example optical is correct , camera forward or backward . But move up or down is incorrect.
thank you , looking forward your reply.

**Comment by zhangjialu11** [comment]
okk~
In this example is correct:
img0
![NewLevelSequence 0016](https://github.com/ydrive/EasySynth/assets/34624669/92c0967b-4d5a-409b-ae4b-82d5efbad3a4)

**Comment by zhangjialu11** [comment]
okk~ thank you reply
in this example is correct:
camera is forward or backward or rotation Z axis (UE coordinate)
img0:
![NewLevelSequence 0016](https://github.com/ydrive/EasySynth/assets/34624669/9a358423-1a8a-4b80-b84a-1bd70de86315)

img1:
![NewLevelSequence 0017](https://github.com/ydrive/EasySynth/assets/34624669/fcfe8a0b-1aec-49f2-9df1-703d6c3c1966)

warp0:
![0warp](https://github.com/ydrive/EasySynth/assets/34624669/98a21726-4ab9-43ec-bc2e-2ba24667f377)
******************************************************************************************
I found in this example is incorrect:
camera  rotation  Y axis (UE coordinate)
img0:

img1:
![1](https://github.com/ydrive/EasySynth/assets/34624669/1b5482a0-16bd-4990-b7f6-5734dffc93d1)

warp0:
![0warp](https://github.com/ydrive/EasySynth/assets/34624669/f5dc0674-454f-43db-a1a1-6c9e4e52e2a1)

I use the same code to test warp. 
I try to solve this problem, but no successful.
I think it's possible that this is caused by the fact that the camera coordinate system of the UE is different from the camera coordinate system in the ideal pinhole camera model. In UE the camera coordinate system is the same as the world coordinate system, but this is not the case for the ideal pinhole camera model

**Comment by zhangjialu11** [comment]
okk~ thank you reply
in this example is correct:
camera is forward or backward or rotation Z axis (UE coordinate)
img0:
![NewLevelSequence 0016](https://github.com/ydrive/EasySynth/assets/34624669/9a358423-1a8a-4b80-b84a-1bd70de86315)

img1:
![NewLevelSequence 0017](https://github.com/ydrive/EasySynth/assets/34624669/fcfe8a0b-1aec-49f2-9df1-703d6c3c1966)

warp0:
![0warp](https://github.com/ydrive/EasySynth/assets/34624669/98a21726-4ab9-43ec-bc2e-2ba24667f377)
******************************************************************************************
I found in this example is incorrect:
camera  rotation  Y axis (UE coordinate)
img0:
![0](https://github.com/ydrive/EasySynth/assets/34624669/619ef824-80d8-496e-b4c0-c231e55cdca2)

img1:
![1](https://github.com/ydrive/EasySynth/assets/34624669/33f2e538-9dd4-474e-ad2c-3d678103cb8d)


warp0:
![0warp](https://github.com/ydrive/EasySynth/assets/34624669/f5dc0674-454f-43db-a1a1-6c9e4e52e2a1)

I use the same code to test warp. 
I try to solve this problem, but no successful.
I think it's possible that this is caused by the fact that the camera coordinate system of the UE is different from the camera coordinate system in the ideal pinhole camera model. In UE the camera coordinate system is the same as the world coordinate system, but this is not the case for the ideal pinhole camera model

**Comment by zhangjialu11** [comment]
hi~, I've solved the problem, thanks for the reply!

**Comment by kaillerC94** [comment]
> hi~, I've solved the problem, thanks for the reply!

Hi, i also encountered this problem. Can you share your solution? Thank you very much.

**Comment by kaillerC94** [comment]
> hi~, I've solved the problem, thanks for the reply!

@ghost hi,I also encountered this problem. Can you share your solution? Thank you very much.
