### ISSUE TITLE
v4.0.1 is not work 

### ISSUE THREAD

**Issue by james-yoo** [ydrive/EasySynth#71]
**Describe the bug**
Release v4.0.1 is not work under UE 5.3.2

**To Reproduce**
I have followed the [installation guide](https://github.com/ydrive/EasySynth?tab=readme-ov-file#install-inside-a-specific-project)

**Expected behavior**
Unreal project opens without any problems.

**Screenshots**
Following error occurs while opening the project.
```
Assertion failed: ModuleManager.IsModuleLoaded(ModuleName) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Modules\ModuleManager.h] [Line: 309] Tried to get module interface for unloaded module: 'ConsoleVariablesEditor'

UnrealEditor_MovieRenderPipelineSettings
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_EasySynth!USequenceRenderer::USequenceRenderer() [C:\Users\jovan\Desktop\EasySynth\HostProject\Plugins\EasySynth\Source\EasySynth\Private\SequenceRenderer.cpp:86]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Projects
UnrealEditor_Projects
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Configuration (if applicable):**
 - OS: Windows 11
 - GPU: NVIDIA RTX 3070 Ti
 - UE version: 5.3.2
 - Used template: Game with C++

**Comment by NikolaJov96** [comment]
Hi @james-yoo,

I haven't seen that issue before. This release was tested on both inside the project and installed through Epic store. I'll try to reproduce it next week.

Can you try rebuilding the project from VisualStudio with the plugin code in place before opening the project in UE?

If you have installed UE through Epic launcher you should be able to install the plugin through the marketplace and see if it works that way.

**Comment by james-yoo** [comment]
Hi @NikolaJov96,
The problem was caused by the same project name and plugin name('EasySynth'). 
Sorry for the confusion. Issue resolved.
